# Generated by Django 5.1.4 on 2025-01-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_remove_notification_item_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
